import { ClerkProvider } from "@clerk/nextjs";
import { Jost, Geist_Mono } from "next/font/google";

import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";

const jost = Jost({
  weight: ["500", "700"], // Add the weights you want to use
  subsets: ["latin"],
  variable: "--font-jost", // Use a more descriptive variable name
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider  signInFallbackRedirectUrl="/workspace"
  signUpFallbackRedirectUrl="/workspace">
      <html lang="en" suppressHydrationWarning>
        <body
  className={`${jost.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Provider>
            <main>{children}</main>
          </Provider>
          <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
