"use client";
import { useUser } from "@clerk/nextjs";
import axios from "axios";
import React, { useEffect, useState } from "react";
import CourseCard from "../_components/CourseCard";
import SkeletonCourseCard from './_components/SkeletonCourseCard'
function ExploreCourses() {
  const [courseList, setCourseList] = useState([]);
  const [loading, setLoading] = useState(true);
  const { user, isLoaded } = useUser();

  useEffect(() => {
    if (isLoaded && user) {
      getCourseContent();
    }
  }, [isLoaded, user]);

  const getCourseContent = async () => {
    try {
      setLoading(true);
      const result = await axios.get("/api/get-course?courseId=0");
      setCourseList(result.data);
    } catch (error) {
      console.error("Failed to fetch courses:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <h2 className="text-2xl font-bold my-2">
        Explore More Courses Generated by the users!
      </h2>

      {loading ? (
        // Skeleton while loading
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {[...Array(6)].map((_, idx) => (
            <SkeletonCourseCard key={idx} />
          ))}
        </div>
      ) : courseList.length === 0 ? (
        <div className="text-center py-12 text-muted-foreground">
          <p className="text-lg font-medium">No courses available</p>
          <p className="text-sm">
            Once you enroll in a course, it will appear here.
          </p>
        </div>
      ) : (
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {courseList.map((course) => (
            <CourseCard key={course.cid} course={course} />
          ))}
        </div>
      )}
    </div>
  );
}

export default ExploreCourses;
