"use client"
import { useUser } from '@clerk/nextjs';
import axios from 'axios';
import React, { useEffect, useState } from 'react'
import CourseCard from '../_components/CourseCard';

function ExploreCourses() {
    const [courseList, setCourseList] = useState([]);
  // ✅ FIX 1: Destructure 'user' and 'isLoaded' from the hook
  const { user, isLoaded } = useUser();

  useEffect(() => {
    // ✅ FIX 3: Check if the user is fully loaded AND exists before fetching
    if (isLoaded && user) {
      getCourseContent();
    }
    // ✅ FIX 2: Change the dependency from [user] to the stable [isLoaded]
  }, [isLoaded, user]); // Depend on both to refetch if the user logs out/in

  const getCourseContent = async () => {
    try {
      const result = await axios.get("/api/get-course?courseId=0");
      setCourseList(result.data);
      console.log(result.data);
    } catch (error) {
      console.error("Failed to fetch courses:", error);
    }
  };
  return (
    <div>
        <h2 className='text-2xl font-bold my-2' >Explore More Courses Generated by the users!</h2>
        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {courseList.map((course) => (
            <CourseCard key={course.cid} course={course} />
          ))}
        </div>

    </div>
  )
}

export default ExploreCourses